# Build and release a docker
name: Docker release
inputs:
  image_base_name:
    required: true
  version:
    required: true
  dockerhub_username:
    required: true
  dockerhub_token:
    required: true
  github_token:
    required: true
  docker_file:
    default: Dockerfile
    required: true

runs:
  using: composite
  steps:
    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v3
      with:
        # list of Docker images to use as base name for tags
        # TODO make more flexible
        images: |
          openclimatefix/${{ inputs.image_base_name }}
        tags: |
          type=raw,value=${{ inputs.version }}
        flavor: |
          latest=true
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ inputs.dockerhub_username }}
        password: ${{ inputs.dockerhub_token }}
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: openclimatefix
        password: ${{ inputs.github_token }}
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ${{ inputs.docker_file }}
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
