name: Branch CI

on:  
  push:
    branches-ignore: [ $default-branch ]
    paths-ignore: ['README.md']

jobs:
  branch_ci:
    uses: openclimatefix/.github/.github/workflows/branch_ci.yml@main
    with:
      enable_typechecking: false
    secrets: inherit
