# Build and publish a python package to PYPI

name: Publish python package
inputs:
  pypi_token:
    required: true
runs:
  using: composite
  steps:
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.x"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build
      shell: bash

    - name: Build package
      run: python -m build
      shell: bash

    - name: Publish package
      uses: pypa/gh-action-pypi-publish@27b31702a0e7fc50959f5ad993c78deac1bdfc29
      with:
        user: __token__
        password: ${{ inputs.pypi_token }}
