# Build and release a docker to Docker Hub

name: Docker release

secrets:
  DOCKERHUB_USERNAME:
    required: true
  DOCKERHUB_TOKEN:
    required: true
inputs:
  image_base_name:
    required: true
    type: string
  docker_file:
    required: false
    type: string
    default: Dockerfile
  tag_value:
    required: true
    type: string
  checkout_submodules:
    description: Forwarded to `submodule` input of the `actions/checkout` step.
    type: boolean
    required: false
    # Default: false
    # See: https://github.com/actions/checkout/tree/v2
    default: false

run:
  steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: main
        submodules: ${{ inputs.checkout_submodules }}
    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v3
      with:
        # list of Docker images to use as base name for tags
        # TODO make more flexible
        images: |
          openclimatefix/${{ inputs.image_base_name }}
        tags: |
          type=raw,value=${{ inputs.tag_value }}
        flavor: |
          latest=true
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: openclimatefix
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ${{ inputs.docker_file }}
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
