name: Make a github release

on:
  workflow_call:
    inputs:
      version:
        description: Version to release, e.g. "1.0.0"
        type: string
        required: true


jobs:
  github-release:
    name: Github release
    runs-on: ubuntu-latest
    steps:
      - name: Echo Deprecation Warning
        run: |
          echo "::warning Deprecated action. Migrate to bump_tag.yml"
          
      - name: Changelog
        uses: scottbrenner/generate-changelog-action@master
        id: Changelog
        env:
          REPO: ${{ github.repository }}

      - name: Create Release
        id: create_release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ inputs.version }}
          release_name: v${{ inputs.version }}
          body: |
            ${{ steps.Changelog.outputs.changelog }}
          draft: false
          prerelease: false
