name: Poetry Lint and Python Tests
on:
  workflow_call:
    inputs:
      pytest_cov_dir:
        required: false
        type: string
        default: 'unassigned'
    secrets:
      HUGGINGFACE_TOKEN:
        required: false
        description: 'Token for private HF repo'

jobs:
  lint_and_test:
    name: Lint the code and run the tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Install poetry
        run: pipx install poetry==1.7.1

      - name: Install python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'poetry'

      - name: Install python dependencies
        run: poetry install

      - name: Lint
        run: make lint

      - name: Run the tests
        run: |
          export HUGGINGFACE_TOKEN=${{ secrets.HUGGINGFACE_TOKEN }}
          poetry run pytest --cov=${{ inputs.pytest_cov_dir }} --cov-report=xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          fail_ci_if_error: false
