name: Python Tests
on:
  workflow_call:
    inputs:
      pytest_cov_dir:
        required: false
        type: string
        default: 'unassigned'
      pytest_numcpus:
        required: false
        type: string
        default: '2'
      sudo_apt_install:
        # this can be set to 'libgeos-dev libproj-dev', so that for a linux machine, these packages are installed.
        required: false
        type: string
        default: ''
      brew_install:
        # for mac machine, these are extra packages that are installed
        required: false
        type: string
        default: 'c-blosc hdf5'
      os_list:
        # which systems to run the tests on
        default: '["ubuntu-latest", "macos-latest"]'
        type: string
        required: false
      python-version:
        description: 'The python versions to use'
        default: "['3.10', '3.11', '3.12']"
        required: false
        type: string
      python_path:
        # add dir to the python path, e.g. './src'
        default: ''
        type: string
        required: false
      extra_commands:
        # Run extra commands (like compiling xgboost)
        default: ''
        type: string
        required: false
      test_dir:
        # Test directory to go into (if needed)
        default: ''
        type: string
        required: false



jobs:
  run-python-tests:
    strategy:
      matrix:
        python-version: ${{ fromJson(inputs.python-version) }}
        os: "${{ fromJSON(inputs.os_list) }}"
    runs-on: ${{ matrix.os }}

    steps:
      - name: Echo Deprecation Warning
        run: |
          echo "::warning Deprecated action. Migrate to branch_ci.yml"

      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
      - name: Do some macOS specific installs for Python 3.9
        run: |
          brew install ${{inputs.brew_install}}
        if: matrix.os == 'macos-latest'
      - name: Do some Ubunutu specific installs for Python 3.9
        if: runner.os == 'Linux' && ${{inputs.sudo_apt_install}} != ''
        run: |
          sudo apt-get update || true
          sudo apt install ${{inputs.sudo_apt_install}}
      - name: Run extra commands
        run: |
          ${{inputs.extra_commands}}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest-xdist
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          if [ -f "setup.py" ]; then pip install -e .; else export PYTHONPATH=$PYTHONPATH:./src; fi
          if [ -f "pyproject.toml" ]; then pip install -e .[docs]; fi
          echo "PYTHONPATH=$PYTHONPATH" >> $GITHUB_ENV
      - name: Setup with pytest-xdist
        run: |
          # lets get the string for how many cpus to use with pytest
          echo "Will be using ${{ inputs.pytest_numcpus }} cpus for pytest testing"
          #
          # make PYTESTXDIST
          export PYTESTXDIST="-n ${{ inputs.pytest_numcpus }}"
          if [ ${{ inputs.pytest_numcpus }} -gt 0 ]; then export PYTESTXDIST="$PYTESTXDIST --dist=loadfile"; fi
          #
          # echo results and save env var for other jobs
          echo "pytest-xdist options that will be used are: $PYTESTXDIST"
          echo "PYTESTXDIST=$PYTESTXDIST" >> $GITHUB_ENV
      - name: Setup with pytest-cov
        run: |
          # let make pytest run with coverage
          echo "Will be looking at coverage of dir  ${{ inputs.pytest_cov_dir }}"
          #
          # install pytest-cov
          pip install coverage
          pip install pytest-cov
          #
          # make PYTESTCOV
          export PYTESTCOV="--cov=${{ inputs.pytest_cov_dir }} --cov-report=xml"
          if [ ${{ inputs.pytest_cov_dir }} == "unassigned" ]; then export PYTESTCOV=""; fi
          #
          # echo results and save env var for other jobs
          echo "pytest-cov options that will be used are: $PYTESTCOV"
          echo "PYTESTCOV=$PYTESTCOV" >> $GITHUB_ENV
      - name: Run pytest
        run: |
          export PYTHONPATH=${PYTHONPATH}:${{ inputs.python_path }}
          export PYTEST_COMMAND="pytest $PYTESTCOV $PYTESTXDIST -s"
          echo "Will be running this command: $PYTEST_COMMAND"
          if [ ${{ inputs.test_dir }} != '' ]; then cd ${{ inputs.test_dir }}; fi
          eval $PYTEST_COMMAND
      - name: Show coverage
        run: |
          if [ ${{ inputs.test_dir }} != '' ]; then cd ${{ inputs.test_dir }}; fi
          coverage report -m
      - name: "Upload coverage to Codecov"
        uses: codecov/codecov-action@v2
        with:
          fail_ci_if_error: false
